spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/crispy_kitchen
    username: zeva
    password: zeva16
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2022260@utsh.edu.mx
    password: qhst rrbo ijfs cnok
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust : smtp.gmail.com

calendly:
  api:
    token: "eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguY2FsZW5kbHkuY29tIiwiaWF0IjoxNzUxNDgyODgzLCJqdGkiOiI4ZTNhYmIzNS0zODM2LTQ3MzUtYmFiNi1jMjEwYjUyZjg2NDUiLCJ1c2VyX3V1aWQiOiJlOTRmNDFjOC02NzRjLTRhYmQtYmVhMi1mNmVlYzBkNTAwYWMifQ.VfOOidMRTkf0aqXV67_GWWzC6F7rS75T6x2vRDmguwy6lMc_eM1dDv8bUPmqgej2s03a-gsREBP6FMs4qhRkmw"


