spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/crispy_kitchen
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_MAIL}
    password: ${STMP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust : smtp.gmail.com

calendly:
  api:
    token: ${CALENDLY_API_TOKEN}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    exipration-time: ${JWT_SECRET_KEY}
